### ISSUE TITLE
automated build ? 

### ISSUE THREAD

**Issue by alamboley** [Blank101/haxe-phaser#47]
Hey,

Thanks for your hard work. Phaser has commited a new version 2.3.0 https://github.com/photonstorm/phaser but this haxe rep hasn't been updated.
It sounds that it already missed the 2.2.2 update.

**Comment by Blank101** [comment]
I'll update the build soon, thanks.

**Comment by alamboley** [comment]
Awesome thanks. I'd some issues running your script.
So I looked some other ways : 
- https://github.com/jgranick/buildhx using YUIDoc (but wasn't able to had the build.xml)
- https://github.com/Simn/ts2hx I'd an issue with the 3rd party lib that I've to use some git.

**Comment by Blank101** [comment]
Yeah I tried some other stuff before building js2hx, but nothing seemed to work for Phaser. Hence why I rolled my own solution.

**Comment by Blank101** [comment]
This is done.

**Comment by alamboley** [comment]
Everything works fine, thanks!
