### ISSUE TITLE
methods missing in components.Core, pixi.DisplayObjectContainer

### ISSUE THREAD

**Issue by Yann-P** [Blank101/haxe-phaser#55]
I've been using this phaser definition for a month and it's *VERY* handy. Autocompletion and compile-time errors have saved me so much time compared to pure js phaser development.

However I found some issues with sprites, they are missing some methods like `update`, `postUpdate` (from gameobjects.components.Core) and several methods from PIXI (like `removeChild` from `pixi.DisplayObjectContainer`).

That surprised me because there is no reason for js2hx to ignore this method compared to `getLocalBounds` (from `pixi.DisplayObjectContainer`) that *is* in the externs and is declared with the exact same syntax in the .js source file.

I also found other issues : 
- functions that use the "arguments"  array in javascript are sometimes defined with no argument in the externs and are impossible to use
- overloads are often incorrect ex. the constructor of Game : 
`function new (?width:String = 800, ?height:String = 600, ?renderer:Float, /*...*/);`

note the String type for width and height
- some constructors are missing (ex `gameobjects.Button`)

I am interested in fixing the externs manually if you want (that's what I've been doing locally on my computer for now, I could become a contributor to this repo) but maybe it would be better to find the issue with js2hx. I'll take a look.

**Comment by Blank101** [comment]
Hey, thanks for your interest in the project. js2hx is far from perfect. Instead I used it as a jumping off point.

I would recommend making manual changes, but feel free to get things fixed in js2hx as well for future major updates. I'll add you as a contributor so you can get started making fixes.
