### ISSUE TITLE
Updates to externs

### ISSUE THREAD

**Issue by Ajacmac** [Blank101/haxe-phaser#58]
Hi, I noticed the externs haven't been updated, and the previous issue about the same. I figured this was the easiest way to get a hold of you (couldn't find contact details on your github profile page), and was wondering if there was anything I could do to help? Is there a bit of process involved in updating? I haven't made externs before, but if it's not beyond an average amateur dev I'd be happy to help.

**Comment by Blank101** [comment]
The difference between the external API between minor version updates is usually pretty small so you can probably just use the newest Phaser version and it will work fine with these externs. Feel free to submit a pull request if you're interested in updating it on here. You will basically just need to update the library version in the lib/ directory and maybe do a look over the API changes in the Phaser versions between 2.4.8 and 2.6.0.

Let me know if you run into any problems. I appreciate the help. :)

**Comment by Ajacmac** [comment]
Awesome. So there have been a couple API changes, I'm assuming that argument changes won't require modifications to the externs, but how do I go about adding new functions entirely? New signals and constants? I'm not sure I will be using (and therefore should care about) the API changes I found looking through, but I'd like to do it for someone else who might want to use them

Thanks!

**Comment by Blank101** [comment]
You can use the other function definitions as an example of how to add new functions. I'm not really sure how to assist you. There is documentation for extern classes in the Haxe documentation.
